spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true